Breakdown score
kumarRaj/stocks pull request #36
Opened 2022-04-15 18:21 UTC by SunandanBose

Problem solved : https://github.com/kumarRaj/stocks/issues/34

2022-04-15 19:04 UTC, kumarRaj commented on backend/src/main/java/com/project/stocks/service/ScoreBuilder.java
> +        int sum = 0;
What does this sum up to? It's just the PE value

2022-04-15 19:06 UTC, kumarRaj commented on backend/src/main/java/com/project/stocks/service/ScoreBuilder.java
> +        score.getScoreBreakdown().setRevenue(value);
This should be borrowings right?

2022-04-15 19:10 UTC, kumarRaj commented on backend/src/main/java/com/project/stocks/service/ScoreBuilder.java
> +        score.getScoreBreakdown().setOperatingProfitMargin(value);
How I would write this code would be to have a score breakdown property in the builder,.
Use `scoreBreakdown.setOperatingProfitMargin(value);` 

Then in the build method just add
`score.setScoreBreakdown(scoreBreakdown);`

2022-04-15 19:12 UTC, kumarRaj commented
Do we still need the vercel deployment?

2022-04-15 19:13 UTC, kumarRaj commented on backend/src/main/java/com/project/stocks/service/ScoreBuilder.java
> +        score.getScoreBreakdown().setPe(sum);
Can we also have tests for score breakdown calculation?

2022-04-15 19:13 UTC, kumarRaj requested changes
Have left comments

2022-04-16 03:50 UTC, SunandanBose commented
yes, I still need vercel deployment. I will fix the UI soon.

2022-04-16 09:49 UTC, kumarRaj approved these changes
Looks good

2022-04-16 09:50 UTC, merged